#!/usr/bin/env bash
# ---------------------------------------------------------------------
# Copyright 2026 ABLECLOUD
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ---------------------------------------------------------------------

# shellcheck disable=SC2034

FTCTL_DEFAULT_CONFIG="/etc/ablestack/ablestack-vm-ftctl.conf"

FTCTL_POLICY_DEFAULT="default"
FTCTL_DRY_RUN_DEFAULT="0"
FTCTL_RUN_DIR_DEFAULT="/run/ablestack-vm-ftctl"
FTCTL_LOG_DIR_DEFAULT="/var/log/ablestack-vm-ftctl"
FTCTL_EVENTS_LOG_DEFAULT="/var/log/ablestack-vm-ftctl/events.log"
FTCTL_LOCK_FILE_DEFAULT="/run/ablestack-vm-ftctl/lock"
FTCTL_STATE_DIR_DEFAULT="/run/ablestack-vm-ftctl/state"
FTCTL_PROFILE_DIR_DEFAULT="/etc/ablestack/ftctl.d"
FTCTL_CLUSTER_CONFIG_DEFAULT="/etc/ablestack/ablestack-vm-ftctl-cluster.conf"
FTCTL_CLUSTER_DIR_DEFAULT="/etc/ablestack/ftctl-cluster.d"
FTCTL_CLUSTER_HOSTS_DIR_DEFAULT="/etc/ablestack/ftctl-cluster.d/hosts"

FTCTL_DEFAULT_PRIMARY_URI_DEFAULT="qemu:///system"
FTCTL_DEFAULT_PEER_URI_DEFAULT="qemu+ssh://peer/system"

FTCTL_HEALTH_INTERVAL_SEC_DEFAULT="2"
FTCTL_FAILOVER_CONFIRM_SEC_DEFAULT="4"
FTCTL_FENCING_TIMEOUT_SEC_DEFAULT="15"
FTCTL_FENCING_SSH_USER_DEFAULT="root"
FTCTL_SSH_PASSWORD_DEFAULT=""
FTCTL_FENCING_IPMI_USER_DEFAULT="root"
FTCTL_FENCING_IPMI_PASSWORD_DEFAULT=""
FTCTL_FENCING_IPMI_INTERFACE_DEFAULT="lanplus"
FTCTL_FAILBACK_DISK_MAP_DEFAULT="source"
FTCTL_FAILBACK_REVERSE_SYNC_TIMEOUT_SEC_DEFAULT="600"
FTCTL_FAILBACK_FINALIZE_TIMEOUT_SEC_DEFAULT="1800"
FTCTL_FAILBACK_REPROTECT_TIMEOUT_SEC_DEFAULT="600"
FTCTL_UNPROTECT_RELEASE_TIMEOUT_SEC_DEFAULT="180"
FTCTL_RBD_PARENT_POLICY_DEFAULT="defer-flatten-on-protect"
FTCTL_RBD_FLATTEN_TIMEOUT_SEC_DEFAULT="3600"
FTCTL_RBD_SPARSIFY_TIMEOUT_SEC_DEFAULT="1800"
FTCTL_THIN_PRESERVE_DEFAULT="1"
FTCTL_THIN_SPARSE_SIZE_DEFAULT="4k"
FTCTL_TRANSIENT_NET_GRACE_SEC_DEFAULT="3"
FTCTL_MAX_REARM_ATTEMPTS_DEFAULT="5"
FTCTL_REARM_BACKOFF_SEC_DEFAULT="2"

FTCTL_BLOCKCOPY_BANDWIDTH_MIB_DEFAULT="0"
FTCTL_BLOCKCOPY_SYNC_WRITES_DEFAULT="1"
FTCTL_BLOCKCOPY_GRANULARITY_DEFAULT="0"
FTCTL_BLOCKCOPY_WAIT_TIMEOUT_SEC_DEFAULT="30"
FTCTL_BLOCKCOPY_TARGET_BASE_DIR_DEFAULT="/var/lib/ablestack-vm-ftctl/blockcopy"
FTCTL_XML_BACKUP_DIR_DEFAULT="/var/lib/ablestack-vm-ftctl/xml"
FTCTL_STANDBY_VERIFY_TIMEOUT_SEC_DEFAULT="20"
FTCTL_REMOTE_NBD_PORT_BASE_DEFAULT="10809"
FTCTL_REMOTE_NBD_PORT_COUNT_DEFAULT="64"
FTCTL_REMOTE_NBD_MAX_CONCURRENT_DEFAULT="64"

FTCTL_XCOLO_QMP_TIMEOUT_SEC_DEFAULT="3"
FTCTL_XCOLO_CONTROL_NET_DEFAULT=""
FTCTL_XCOLO_REPL_NET_DEFAULT=""

FTCTL_CONFIG_PATH=""
FTCTL_POLICY=""
FTCTL_DRY_RUN=""
FTCTL_RUN_DIR=""
FTCTL_LOG_DIR=""
FTCTL_EVENTS_LOG=""
FTCTL_LOCK_FILE=""
FTCTL_STATE_DIR=""
FTCTL_PROFILE_DIR=""
FTCTL_CLUSTER_CONFIG=""
FTCTL_CLUSTER_DIR=""
FTCTL_CLUSTER_HOSTS_DIR=""
FTCTL_DEFAULT_PRIMARY_URI=""
FTCTL_DEFAULT_PEER_URI=""
FTCTL_HEALTH_INTERVAL_SEC=""
FTCTL_FAILOVER_CONFIRM_SEC=""
FTCTL_FENCING_TIMEOUT_SEC=""
FTCTL_FENCING_SSH_USER=""
FTCTL_SSH_PASSWORD=""
FTCTL_FENCING_IPMI_USER=""
FTCTL_FENCING_IPMI_PASSWORD=""
FTCTL_FENCING_IPMI_INTERFACE=""
FTCTL_FAILBACK_DISK_MAP=""
FTCTL_FAILBACK_REVERSE_SYNC_TIMEOUT_SEC=""
FTCTL_FAILBACK_FINALIZE_TIMEOUT_SEC=""
FTCTL_FAILBACK_REPROTECT_TIMEOUT_SEC=""
FTCTL_UNPROTECT_RELEASE_TIMEOUT_SEC=""
FTCTL_RBD_PARENT_POLICY=""
FTCTL_RBD_FLATTEN_TIMEOUT_SEC=""
FTCTL_RBD_SPARSIFY_TIMEOUT_SEC=""
FTCTL_THIN_PRESERVE=""
FTCTL_THIN_SPARSE_SIZE=""
FTCTL_TRANSIENT_NET_GRACE_SEC=""
FTCTL_MAX_REARM_ATTEMPTS=""
FTCTL_REARM_BACKOFF_SEC=""
FTCTL_BLOCKCOPY_BANDWIDTH_MIB=""
FTCTL_BLOCKCOPY_SYNC_WRITES=""
FTCTL_BLOCKCOPY_GRANULARITY=""
FTCTL_BLOCKCOPY_WAIT_TIMEOUT_SEC=""
FTCTL_BLOCKCOPY_TARGET_BASE_DIR=""
FTCTL_XML_BACKUP_DIR=""
FTCTL_STANDBY_VERIFY_TIMEOUT_SEC=""
FTCTL_REMOTE_NBD_PORT_BASE=""
FTCTL_REMOTE_NBD_PORT_COUNT=""
FTCTL_REMOTE_NBD_MAX_CONCURRENT=""
FTCTL_XCOLO_QMP_TIMEOUT_SEC=""
FTCTL_XCOLO_CONTROL_NET=""
FTCTL_XCOLO_REPL_NET=""

ftctl_config_init_defaults() {
  FTCTL_CONFIG_PATH="${FTCTL_DEFAULT_CONFIG}"
  FTCTL_POLICY="${FTCTL_POLICY_DEFAULT}"
  FTCTL_DRY_RUN="${FTCTL_DRY_RUN_DEFAULT}"
  FTCTL_RUN_DIR="${FTCTL_RUN_DIR_DEFAULT}"
  FTCTL_LOG_DIR="${FTCTL_LOG_DIR_DEFAULT}"
  FTCTL_EVENTS_LOG="${FTCTL_EVENTS_LOG_DEFAULT}"
  FTCTL_LOCK_FILE="${FTCTL_LOCK_FILE_DEFAULT}"
  FTCTL_STATE_DIR="${FTCTL_STATE_DIR_DEFAULT}"
  FTCTL_PROFILE_DIR="${FTCTL_PROFILE_DIR_DEFAULT}"
  FTCTL_CLUSTER_CONFIG="${FTCTL_CLUSTER_CONFIG_DEFAULT}"
  FTCTL_CLUSTER_DIR="${FTCTL_CLUSTER_DIR_DEFAULT}"
  FTCTL_CLUSTER_HOSTS_DIR="${FTCTL_CLUSTER_HOSTS_DIR_DEFAULT}"
  FTCTL_DEFAULT_PRIMARY_URI="${FTCTL_DEFAULT_PRIMARY_URI_DEFAULT}"
  FTCTL_DEFAULT_PEER_URI="${FTCTL_DEFAULT_PEER_URI_DEFAULT}"
  FTCTL_HEALTH_INTERVAL_SEC="${FTCTL_HEALTH_INTERVAL_SEC_DEFAULT}"
  FTCTL_FAILOVER_CONFIRM_SEC="${FTCTL_FAILOVER_CONFIRM_SEC_DEFAULT}"
  FTCTL_FENCING_TIMEOUT_SEC="${FTCTL_FENCING_TIMEOUT_SEC_DEFAULT}"
  FTCTL_FENCING_SSH_USER="${FTCTL_FENCING_SSH_USER_DEFAULT}"
  FTCTL_SSH_PASSWORD="${FTCTL_SSH_PASSWORD_DEFAULT}"
  FTCTL_FENCING_IPMI_USER="${FTCTL_FENCING_IPMI_USER_DEFAULT}"
  FTCTL_FENCING_IPMI_PASSWORD="${FTCTL_FENCING_IPMI_PASSWORD_DEFAULT}"
  FTCTL_FENCING_IPMI_INTERFACE="${FTCTL_FENCING_IPMI_INTERFACE_DEFAULT}"
  FTCTL_FAILBACK_DISK_MAP="${FTCTL_FAILBACK_DISK_MAP_DEFAULT}"
  FTCTL_FAILBACK_REVERSE_SYNC_TIMEOUT_SEC="${FTCTL_FAILBACK_REVERSE_SYNC_TIMEOUT_SEC_DEFAULT}"
  FTCTL_FAILBACK_FINALIZE_TIMEOUT_SEC="${FTCTL_FAILBACK_FINALIZE_TIMEOUT_SEC_DEFAULT}"
  FTCTL_FAILBACK_REPROTECT_TIMEOUT_SEC="${FTCTL_FAILBACK_REPROTECT_TIMEOUT_SEC_DEFAULT}"
  FTCTL_UNPROTECT_RELEASE_TIMEOUT_SEC="${FTCTL_UNPROTECT_RELEASE_TIMEOUT_SEC_DEFAULT}"
  FTCTL_RBD_PARENT_POLICY="${FTCTL_RBD_PARENT_POLICY_DEFAULT}"
  FTCTL_RBD_FLATTEN_TIMEOUT_SEC="${FTCTL_RBD_FLATTEN_TIMEOUT_SEC_DEFAULT}"
  FTCTL_RBD_SPARSIFY_TIMEOUT_SEC="${FTCTL_RBD_SPARSIFY_TIMEOUT_SEC_DEFAULT}"
  FTCTL_THIN_PRESERVE="${FTCTL_THIN_PRESERVE_DEFAULT}"
  FTCTL_THIN_SPARSE_SIZE="${FTCTL_THIN_SPARSE_SIZE_DEFAULT}"
  FTCTL_TRANSIENT_NET_GRACE_SEC="${FTCTL_TRANSIENT_NET_GRACE_SEC_DEFAULT}"
  FTCTL_MAX_REARM_ATTEMPTS="${FTCTL_MAX_REARM_ATTEMPTS_DEFAULT}"
  FTCTL_REARM_BACKOFF_SEC="${FTCTL_REARM_BACKOFF_SEC_DEFAULT}"
  FTCTL_BLOCKCOPY_BANDWIDTH_MIB="${FTCTL_BLOCKCOPY_BANDWIDTH_MIB_DEFAULT}"
  FTCTL_BLOCKCOPY_SYNC_WRITES="${FTCTL_BLOCKCOPY_SYNC_WRITES_DEFAULT}"
  FTCTL_BLOCKCOPY_GRANULARITY="${FTCTL_BLOCKCOPY_GRANULARITY_DEFAULT}"
  FTCTL_BLOCKCOPY_WAIT_TIMEOUT_SEC="${FTCTL_BLOCKCOPY_WAIT_TIMEOUT_SEC_DEFAULT}"
  FTCTL_BLOCKCOPY_TARGET_BASE_DIR="${FTCTL_BLOCKCOPY_TARGET_BASE_DIR_DEFAULT}"
  FTCTL_XML_BACKUP_DIR="${FTCTL_XML_BACKUP_DIR_DEFAULT}"
  FTCTL_STANDBY_VERIFY_TIMEOUT_SEC="${FTCTL_STANDBY_VERIFY_TIMEOUT_SEC_DEFAULT}"
  FTCTL_REMOTE_NBD_PORT_BASE="${FTCTL_REMOTE_NBD_PORT_BASE_DEFAULT}"
  FTCTL_REMOTE_NBD_PORT_COUNT="${FTCTL_REMOTE_NBD_PORT_COUNT_DEFAULT}"
  FTCTL_REMOTE_NBD_MAX_CONCURRENT="${FTCTL_REMOTE_NBD_MAX_CONCURRENT_DEFAULT}"
  FTCTL_XCOLO_QMP_TIMEOUT_SEC="${FTCTL_XCOLO_QMP_TIMEOUT_SEC_DEFAULT}"
  FTCTL_XCOLO_CONTROL_NET="${FTCTL_XCOLO_CONTROL_NET_DEFAULT}"
  FTCTL_XCOLO_REPL_NET="${FTCTL_XCOLO_REPL_NET_DEFAULT}"
}

ftctl_config_apply_cli() {
  local cfg="${1-}"
  local pol="${2-}"
  local dry="${3-}"
  [[ -n "${cfg}" ]] && FTCTL_CONFIG_PATH="${cfg}"
  [[ -n "${pol}" ]] && FTCTL_POLICY="${pol}"
  [[ -n "${dry}" ]] && FTCTL_DRY_RUN="${dry}"
  return 0
}

ftctl_config_load_file() {
  local path="${1-}"
  [[ -n "${path}" && -f "${path}" ]] || return 0
  set -a
  # shellcheck source=/dev/null
  source "${path}"
  set +a
}

ftctl_config_finalize_paths() {
  if [[ -z "${FTCTL_LOCK_FILE}" || "${FTCTL_LOCK_FILE}" == "${FTCTL_LOCK_FILE_DEFAULT}" ]]; then
    FTCTL_LOCK_FILE="${FTCTL_RUN_DIR}/lock"
  fi
  if [[ -z "${FTCTL_STATE_DIR}" || "${FTCTL_STATE_DIR}" == "${FTCTL_STATE_DIR_DEFAULT}" ]]; then
    FTCTL_STATE_DIR="${FTCTL_RUN_DIR}/state"
  fi
  if [[ -z "${FTCTL_EVENTS_LOG}" || "${FTCTL_EVENTS_LOG}" == "${FTCTL_EVENTS_LOG_DEFAULT}" ]]; then
    FTCTL_EVENTS_LOG="${FTCTL_LOG_DIR}/events.log"
  fi
  if [[ -z "${FTCTL_CLUSTER_HOSTS_DIR}" || "${FTCTL_CLUSTER_HOSTS_DIR}" == "${FTCTL_CLUSTER_HOSTS_DIR_DEFAULT}" ]]; then
    FTCTL_CLUSTER_HOSTS_DIR="${FTCTL_CLUSTER_DIR}/hosts"
  fi
}

ftctl_ensure_runtime_dirs() {
  ftctl_ensure_dir "${FTCTL_RUN_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_RUN_DIR}/locks" "0755"
  ftctl_ensure_dir "${FTCTL_LOG_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_STATE_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_PROFILE_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_CLUSTER_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_CLUSTER_HOSTS_DIR}" "0755"
  ftctl_ensure_dir "$(dirname "${FTCTL_EVENTS_LOG}")" "0755"
  ftctl_ensure_dir "${FTCTL_BLOCKCOPY_TARGET_BASE_DIR}" "0755"
  ftctl_ensure_dir "${FTCTL_XML_BACKUP_DIR}" "0755"
}
